# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'BitnetVehicle' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

    pod 'RxSwift', '5.0.0'
    pod 'RxCocoa', '5.0.0'
    pod 'RxDataSources'

  # Pods for BitnetVehicle

  target 'BitnetVehicleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BitnetVehicleUITests' do
    # Pods for testing
  end

end
